name: CI
on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # otherwise fails to push refs to dest repo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python packages
        run: |
          pip install --upgrade pip
          pip install .[dev]

      # -------------------
      # Install node
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.x
          cache: npm

      - name: Install node packages
        run: npm ci

      # -------------------
      # Compile typescript code
      - name: Compile tracker client
        run: npm run build

      - name: Run Tests
        run: |
          pytest --cov=raitracker test/. --cov-report=html --cov-report=term

      - name: Upload code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: raitracker-code-coverage-results
          path: htmlcov
        if: ${{ always() }}

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.python-version == '3.9'}}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          #files: ./coverage
          verbose: true
